### ISSUE TITLE
Bandpass Filter Direct form I (Avoiding Jitter)

### ISSUE THREAD

**Issue by Mas313** [Cuda-Chen/liquid-dsp-practice#1]
Hi,
Following your post on band pass filter at https://www.reddit.com/r/DSP/comments/gx0tni/bandpass_filter_with_liquiddsp_produces_jitter/

What parameter you have changed in your provided code at https://github.com/jgaeddert/liquid-dsp/blob/master/examples/iirdes_example.c    to change from Direct form II to I to avoid jitter in the band pass filter using liquid dsp.

Thanks

**Comment by Cuda-Chen** [comment]
Hi @Mas313 ,

> What parameter you have changed in your provided code at https://github.com/jgaeddert/liquid-dsp/blob/master/examples/iirdes_example.c to change from Direct form II to I to avoid jitter in the band pass filter using liquid dsp.

I apply a change in the fork of `liquid-dsp`: https://github.com/Cuda-Chen/liquid-dsp/commit/fb0bc6c0f15e1838be0749db665394d26ed282b2

If you need more information please let me know.

**Comment by Mas313** [comment]
Thanks for the reply. 
I did not make any changes  I just looked at your implementation. 
Now what I understand is that I need to recompile with the modification as you have mentioned.
Thanks alot

**Comment by Mas313** [comment]
I want your expert opinion on liquid-dsp gmsk famesync example.  Can you comment on this
`https://github.com/jgaeddert/liquid-dsp/issues/378`

**Comment by Cuda-Chen** [comment]
Hi @Mas313 ,

I am not familiar with the gmsk part. Sorry for your inconvenience .
